# -*- coding: utf-8 -*-
"""FDA_ExcelToJson.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YdZE0kKYCc5lE1AqqiV1k5JjcgmquzKW
"""

import io
import xlrd
from google.colab import files
uploaded = files.upload()

import pandas

df =pandas.read_excel('fda-3.xlsx')
df.loc[1,:]

final_json_array = []

for i in range(0, 77):
  evidence_array = []
  disease_array = []
  drug_array = []
  molecular_entity_array = []
  #has_evidence segment starts
  evidence_segment = {
      "biolink:id": "",
      "biolink:EvidenceType": "FDA",
      "biolink:comment": ""
    }
  evidence_array.append(evidence_segment)
  #--------------------------------------
  #has_disease segment starts
  disease_segment = {
      "biolink:id": [
        {
         "biolink:source_data_file": "EFO",
          "code": str(df.iloc[i, 13]),
          "biolink:source_version": ""
        }
      ],
      "biolink:name": df.iloc[i, 5],
      "biolink:type": "biolink:disease",
      "biolink:comment": df.iloc[i, 5]
    }
  #disease_array.append(disease_segment)
  #--------------------------------------
  #has_drug segment starts
  drugbank_array = str(df.iloc[i, 2]).split(", ")
  pubchem_array = str(df.iloc[i, 3]).split(", ")
  drugname_array = str(df.iloc[i, 1]).split(", ")
  for j in range(0, len(drugbank_array)):
    drug_segment = {
      "biolink:id": [
        {
          "biolink:source_data_file": "Drugbank",
          "code": drugbank_array[j],
          "biolink:versionOf": ""
        },
       {
          "biolink:source_data_file": "PubChem",
          "code": pubchem_array[j],
          "biolink:versionOf": ""
        }
      ],
      "biolink:name": drugname_array[j],
      "biolink:type": "biolink:drug"
    }
    drug_array.append(drug_segment)
  #--------------------------------------
  #has_molecular_entity segment starts
  ensemble_std_array = str(df.iloc[i, 12]).split(",")
  relationship_array = str(df.iloc[i, 8]). split(",")
  marker_type_array = str(df.iloc[i, 10]).split(",")
  enrichment_marker_array = str(df.iloc[i, 6]).split(",")
  for j in range(0, len(ensemble_std_array)):
    molecular_entity_segment = {
      "biolink:id": {
        "biolink:source_data_file": "NCBI Entrez",
        "code": ensemble_std_array[j]
        },
      "biolink:name": enrichment_marker_array[j],
      "biolink:type": marker_type_array[j],
      "biolink:relation": relationship_array[j]
    }
    molecular_entity_array.append(molecular_entity_segment)
  final_json = {
      "biolink:id": "FDA000"+str(i+1),
      "biolink:name": "FDAbiomarker"+str(i+1),
      "biolink:type": "biomarker",
      "curator": [
      {
        "biolink:name": "Ben Feng",
        "biolink:update_date": "2020-02-22T19:41:44.731Z",
        "biolink:comment": "" 
      }
      ],
      "biolink:has_drug": drug_array,
      "has_disease": disease_array,
      "has_molecular_entity": molecular_entity_array,
      "biolink:has_evidence": evidence_array
  }
  #print(final_json)
  final_json_array.append(final_json)

import json
print(json.dumps(final_json_array, sort_keys=True, indent=4))